# =====================================================================
# ZKT Connector - start automatically with Windows (no login needed).
# Creates a Windows Scheduled Task "ZKT Connector" that runs as SYSTEM at
# start-up and restarts the connector if it ever stops.
#
# Run in PowerShell opened with "Run as administrator", from the connector folder:
#   powershell -ExecutionPolicy Bypass -File .\scripts\install-autostart.ps1
# =====================================================================
$ErrorActionPreference = "Stop"
$TaskName = "ZKT Connector"

$me = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $me.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Please open PowerShell with 'Run as administrator' and run this again."
}

$dir = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
if (-not (Test-Path (Join-Path $dir ".env")))         { throw ".env not found in $dir - create it first (see .env.example)." }
$node = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $node) { throw "Node.js was not found in PATH." }

$logs    = Join-Path $dir "logs"
$logFile = Join-Path $logs "connector.log"
$script  = Join-Path $dir "src\index.js"
$cmdPath = Join-Path $dir "run-connector.cmd"
New-Item -ItemType Directory -Force -Path $logs | Out-Null

# Stop an older copy started by this task, if any.
Get-CimInstance Win32_Process |
    Where-Object { $_.CommandLine -and ($_.CommandLine -like "*$script*" -or $_.CommandLine -like "*$cmdPath*") } |
    ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }

# Wrapper: runs the connector, appends output to logs\connector.log,
# keeps the log under ~5 MB, and restarts after 60 s if node exits.
$cmd = @"
@echo off
rem Generated by scripts\install-autostart.ps1 - do not edit, run the installer again instead.
cd /d "$dir"
:loop
for %%F in ("$logFile") do if %%~zF GTR 5000000 move /y "$logFile" "$logFile.old" >nul
echo ===== %date% %time% starting connector >> "$logFile"
"$node" "$script" >> "$logFile" 2>&1
ping -n 61 127.0.0.1 >nul
goto loop
"@
# cmd.exe needs Windows (CRLF) line endings for labels/goto to work.
[System.IO.File]::WriteAllText($cmdPath, ($cmd -replace "`r?`n", "`r`n"), [System.Text.Encoding]::ASCII)

$action    = New-ScheduledTaskAction -Execute "cmd.exe" -Argument "/c `"$cmdPath`"" -WorkingDirectory $dir
$trigger   = New-ScheduledTaskTrigger -AtStartup
$settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable `
               -ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) `
               -MultipleInstances IgnoreNew
$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal `
    -Description "Imports attendance from the ZKTeco machine into HR Attendance Fetcher ($dir)" -Force | Out-Null
Start-ScheduledTask -TaskName $TaskName

Write-Host "Scheduled task '$TaskName' installed and started." -ForegroundColor Green
Write-Host "Waiting 10 seconds for the first log lines..."
Start-Sleep -Seconds 10
if (Test-Path $logFile) { Get-Content $logFile -Tail 12 } else { Write-Host "No log yet: $logFile" -ForegroundColor Yellow }
Write-Host ""
Write-Host "Log file : $logFile"
Write-Host "Status   : Get-ScheduledTask '$TaskName' | Get-ScheduledTaskInfo"
Write-Host "Remove   : powershell -ExecutionPolicy Bypass -File .\scripts\uninstall-autostart.ps1"